app = "lurna-ai"
primary_region = "dfw"

[build]

[env]
  NODE_ENV = "production"
  PORT = "3001"
  FLY_APP_NAME = "lurna-ai"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  interval = "15s"
  grace_period = "10s"
  method = "GET"
  path = "/api/health"
  protocol = "http"
  timeout = "10s"
  tls_skip_verify = false

[machine]
  auto_start_machines = true
  auto_stop_machines = "stop"
  min_machines_running = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[[mounts]]
  source = "lurna_data"
  destination = "/data"
  initial_size = "1gb"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/static/"